//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public class CfgHeroMgr
{
	public Dictionary<int,CfgHero> heroList = new Dictionary<int, CfgHero>();
	private static CfgHeroMgr s_Instance = null;
	private CfgFileMgr m_fileMgr = new CfgFileMgr();
	private string m_strDefaultPath = "";

	private CfgHeroMgr ()
	{
		m_strDefaultPath = Application.dataPath + "/Data/Configs/";
	}

	static public CfgHeroMgr getInstance()
	{
		if(s_Instance==null)
			s_Instance = new CfgHeroMgr();
		return s_Instance;
	}

	public void clear()
	{
	}

	public bool checkId(int id)
	{
		if(id <=0)
			return false;
		CfgHero hero;
		if(heroList.TryGetValue(id,out hero))
			return false;
		return true;
	}

	//添加对象
	public bool addHero(CfgHero hero)
	{
		if(!checkId(hero.getId()))
			return false;
		heroList.Add(hero.getId(),hero);
		return true;
	}

	public bool updateHero(CfgHero hero)
	{
		heroList[hero.getId()] = hero;
		return true;
	}

	//删除对象
	public bool delHero(int nKey)
	{
		return heroList.Remove(nKey);
	}

	//保存
	public bool save()
	{
		if(!m_fileMgr.havePath())
		{
			if(!m_fileMgr.saveBrower("save as",m_strDefaultPath,"HeroCfg","csv"))
				return false;
		}

		string strContent = "";

		for(CfgHero.HERO_PROP i = CfgHero.HERO_PROP.HERO_PROP_ID;i<CfgHero.HERO_PROP.HERO_PROP_UNKOWN;i++)
		{
			CfgHero.HERO_COL col = CfgHero.getCol(i);
			if(col!=null)
			{
				strContent += col.showName;
				strContent += ",";
			}
		}
		//组包
		foreach(KeyValuePair<int,CfgHero> it in heroList)
		{
			strContent += "\r\n";
			CfgHero hero = it.Value;
			for(CfgHero.HERO_PROP i = CfgHero.HERO_PROP.HERO_PROP_ID;i<CfgHero.HERO_PROP.HERO_PROP_UNKOWN;i++)
			{
				if(hero.getColStr(i)!=null)
				{
					if(i!= CfgHero.HERO_PROP.HERO_PROP_ID)
						strContent += ",";
					strContent += hero.getColStr(i);
				}
			}
		}
		return m_fileMgr.WriteFile(strContent);
	}

	public bool load()
	{
		if(!m_fileMgr.openBrower("open config",m_strDefaultPath,"csv"))
			return false;
		StreamReader stream= m_fileMgr.LoadFileStream();
		if(stream==null)
			return false;

        FileHelper reader = new FileHelper();
        bool bRet = reader.open(stream);
        if (!bRet)
        {
            Debug.Log("加载文件:" + m_strDefaultPath + "失败!");
            return false;
        }
        stream.Close();

		heroList.Clear();
		//解析
		int line = reader.rowAmount;
		for(int y=1;y < line;y++)
		{
			int x = 0;
			CfgHero hero = new CfgHero();
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_ID,reader.getInt(y,x++,0));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_NAME,reader.getStr(y,x++));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_PREFABS,reader.getStr(y,x++));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_PREFABPATH,reader.getStr(y,x++));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_TYPE,reader.getInt(y,x++,0));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_HP,reader.getInt(y,x++,0));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_FIRERANGE,reader.getFloat(y,x++,0));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_DAMAGERANGE,reader.getFloat(y,x++,0));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_MOVESPEED,reader.getFloat(y,x++,0));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_DAMAGE,reader.getInt(y,x++,0));
			hero.addCol(CfgHero.HERO_PROP.HERO_PROP_DEFENSE,reader.getInt(y,x++,0));
			addHero(hero);
		}
		stream.Close();
		stream.Dispose();
		return true;
	}
	
	public bool saveAs()
	{
		if(!m_fileMgr.saveBrower("save as",m_strDefaultPath,"HeroCfg","csv"))
			return false;
		return save();
	}

	public CfgHero getHero(int nKey)
	{
		CfgHero hero;
		if(heroList.TryGetValue(nKey,out hero))
			return hero;
		return null;
	}

	public CfgHero getHero(string strKey)
	{
		return null;
	}

	public void release()
	{
		heroList.Clear();
		s_Instance = null;
	}
}

