//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class CfgSoldierMgr
{
	public Dictionary<int,CfgSoldier> soldierList = new Dictionary<int, CfgSoldier>();
	private static CfgSoldierMgr s_Instance = null;
	private CfgFileMgr m_fileMgr = new CfgFileMgr();
	private string m_strDefaultPath = "";

	private CfgSoldierMgr ()
	{
		m_strDefaultPath = 	Application.dataPath + "/Data/Configs/";
	}

	static public CfgSoldierMgr getInstance()
	{
		if(s_Instance==null)
			s_Instance = new CfgSoldierMgr();
		return s_Instance;
	}

	public void clear()
	{
	}

	public bool checkId(int id)
	{
		if(id <=0)
			return false;
		CfgSoldier soldier;
		if(soldierList.TryGetValue(id,out soldier))
			return false;
		return true;
	}

	//添加对象
	public bool addSoldier(CfgSoldier soldier)
	{
		if(!checkId(soldier.getId()))
			return false;
		soldierList.Add(soldier.getId(),soldier);
		return true;
	}

	public bool updateSoldier(CfgSoldier soldier)
	{
		soldierList[soldier.getId()] = soldier;
		return true;
	}

	//删除对象
	public bool delSoldier(int nKey)
	{
		return soldierList.Remove(nKey);
	}

	//保存
	public bool save()
	{
		if(!m_fileMgr.havePath())
		{
			if(!m_fileMgr.saveBrower("save as",m_strDefaultPath,"SoldierCfg","csv"))
				return false;
		}

		string strContent = "";

		for(CfgSoldier.SOLDIER_PROP i = CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_ID;i<CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_UNKOWN;i++)
		{
			CfgSoldier.SOLDIER_COL col = CfgSoldier.getCol(i);
			if(col!=null)
			{
				strContent += col.showName;
				strContent += ",";
			}
		}
		//组包
		foreach(KeyValuePair<int,CfgSoldier> it in soldierList)
		{
			strContent += "\r\n";
			CfgSoldier soldier = it.Value;
			for(CfgSoldier.SOLDIER_PROP i = CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_ID;i<CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_UNKOWN;i++)
			{
				if(soldier.getColStr(i)!=null)
				{
					if(i!= CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_ID)
						strContent += ",";
					strContent += soldier.getColStr(i);
				}
			}
		}
		return m_fileMgr.WriteFile(strContent);
	}

	public bool load()
	{
		if(!m_fileMgr.openBrower("open config",m_strDefaultPath,"csv"))
			return false;
		StreamReader stream= m_fileMgr.LoadFileStream();
		if(stream==null)
			return false;

        FileHelper reader = new FileHelper();
        bool bRet = reader.open(stream);
        if (!bRet)
        {
            Debug.Log("加载文件:" + m_strDefaultPath + "失败!");
            return false;
        }
        stream.Close();

		soldierList.Clear();
		//解析
		int line = reader.rowAmount;
		for(int y=1;y < line;y++)
		{
			int x = 0;
			CfgSoldier soldier = new CfgSoldier();
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_ID,reader.getInt(y,x++,0));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_NAME,reader.getStr(y,x++));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_PREFABS,reader.getStr(y,x++));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_PREFABPATH,reader.getStr(y,x++));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_TYPE,reader.getInt(y,x++,0));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_HP,reader.getInt(y,x++,0));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_FIRERANGE,reader.getFloat(y,x++,0));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_DAMAGERANGE,reader.getFloat(y,x++,0));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_MOVESPEED,reader.getFloat(y,x++,0));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_DAMAGE,reader.getInt(y,x++,0));
			soldier.addCol(CfgSoldier.SOLDIER_PROP.SOLDIER_PROP_DEFENSE,reader.getInt(y,x++,0));
			addSoldier(soldier);
		}
		stream.Close();
		stream.Dispose();
		return true;
	}
	
	public bool saveAs()
	{
		if(!m_fileMgr.saveBrower("save as",m_strDefaultPath,"SoldierCfg","csv"))
			return false;
		return save();
	}

	public CfgSoldier getSoldier(int nKey)
	{
		CfgSoldier soldier;
		if(soldierList.TryGetValue(nKey,out soldier))
			return soldier;
		return null;
	}

	public void release()
	{
		soldierList.Clear();
		s_Instance = null;
	}
}

